kramdown:
  auto_ids:   true
  input:      GFM
exclude:
  - node_modules
baseurl: /
domain_name: 'http://trailblazer.to'
url: 'http://trailblazer.to'
name: "Trailblazer"
imageurl: "http://trailblazer.to/images/go-trailblazer.jpg"
twitter: "@apotonick"
include:
  - .nojekyll